#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libtheora
Version  : 1.1.1
Release  : 1
URL      : http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
Source0  : http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
Summary  : Development tools for Theora applications.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libtheora-lib
Requires: libtheora-doc
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(ogg)
BuildRequires : pkgconfig(vorbis)
BuildRequires : python-dev
BuildRequires : scons
Patch1: 0001-Change-png_sizeof-by-sizeof-function.patch

%description
Theora is Xiph.Org's first publicly released video codec, intended
for use within the Ogg's project's Ogg multimedia streaming system.
Theora is derived directly from On2's VP3 codec; Currently the two are
nearly identical, varying only in encapsulating decoder tables in the
bitstream headers, but Theora will make use of this extra freedom
in the future to improve over what is possible with VP3.

%package dev
Summary: dev components for the libtheora package.
Group: Development
Requires: libtheora-lib
Provides: libtheora-devel

%description dev
dev components for the libtheora package.


%package doc
Summary: doc components for the libtheora package.
Group: Documentation

%description doc
doc components for the libtheora package.


%package lib
Summary: lib components for the libtheora package.
Group: Libraries

%description lib
lib components for the libtheora package.


%prep
%setup -q -n libtheora-1.1.1
%patch1 -p1

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/theora/codec.h
/usr/include/theora/theora.h
/usr/include/theora/theoradec.h
/usr/include/theora/theoraenc.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libtheora/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
