#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libtheora
Version  : 1.1.1
Release  : 9
URL      : http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
Source0  : http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
Summary  : Development tools for Theora applications.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libtheora-lib
Requires: libtheora-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32libpng)
BuildRequires : pkgconfig(32ogg)
BuildRequires : pkgconfig(32vorbis)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(ogg)
BuildRequires : pkgconfig(vorbis)

BuildRequires : scons
BuildRequires : zlib-dev32
Patch1: 0001-Change-png_sizeof-by-sizeof-function.patch

%description
Theora is Xiph.Org's first publicly released video codec, intended
for use within the Ogg's project's Ogg multimedia streaming system.
Theora is derived directly from On2's VP3 codec; Currently the two are
nearly identical, varying only in encapsulating decoder tables in the
bitstream headers, but Theora will make use of this extra freedom
in the future to improve over what is possible with VP3.

%package dev
Summary: dev components for the libtheora package.
Group: Development
Requires: libtheora-lib
Provides: libtheora-devel

%description dev
dev components for the libtheora package.


%package dev32
Summary: dev32 components for the libtheora package.
Group: Default
Requires: libtheora-lib32
Requires: libtheora-dev

%description dev32
dev32 components for the libtheora package.


%package doc
Summary: doc components for the libtheora package.
Group: Documentation

%description doc
doc components for the libtheora package.


%package lib
Summary: lib components for the libtheora package.
Group: Libraries

%description lib
lib components for the libtheora package.


%package lib32
Summary: lib32 components for the libtheora package.
Group: Default

%description lib32
lib32 components for the libtheora package.


%prep
%setup -q -n libtheora-1.1.1
%patch1 -p1
pushd ..
cp -a libtheora-1.1.1 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1501861951
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1501861951
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/theora/codec.h
/usr/include/theora/theora.h
/usr/include/theora/theoradec.h
/usr/include/theora/theoraenc.h
/usr/lib64/libtheora.so
/usr/lib64/libtheoradec.so
/usr/lib64/libtheoraenc.so
/usr/lib64/pkgconfig/theora.pc
/usr/lib64/pkgconfig/theoradec.pc
/usr/lib64/pkgconfig/theoraenc.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libtheora.so
/usr/lib32/libtheoradec.so
/usr/lib32/libtheoraenc.so
/usr/lib32/pkgconfig/32theora.pc
/usr/lib32/pkgconfig/32theoradec.pc
/usr/lib32/pkgconfig/32theoraenc.pc
/usr/lib32/pkgconfig/theora.pc
/usr/lib32/pkgconfig/theoradec.pc
/usr/lib32/pkgconfig/theoraenc.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libtheora/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtheora.so.0
/usr/lib64/libtheora.so.0.3.10
/usr/lib64/libtheoradec.so.1
/usr/lib64/libtheoradec.so.1.1.4
/usr/lib64/libtheoraenc.so.1
/usr/lib64/libtheoraenc.so.1.1.2

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libtheora.so.0
/usr/lib32/libtheora.so.0.3.10
/usr/lib32/libtheoradec.so.1
/usr/lib32/libtheoradec.so.1.1.4
/usr/lib32/libtheoraenc.so.1
/usr/lib32/libtheoraenc.so.1.1.2
